// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// compute_sigma_inp_k_pq_cpp
double compute_sigma_inp_k_pq_cpp(unsigned int k, arma::mat d, arma::mat As, arma::mat Bs, arma::mat prev_ys, arma::mat prev_sigmas, unsigned int p, unsigned int q, int M);
RcppExport SEXP _CurVol_compute_sigma_inp_k_pq_cpp(SEXP kSEXP, SEXP dSEXP, SEXP AsSEXP, SEXP BsSEXP, SEXP prev_ysSEXP, SEXP prev_sigmasSEXP, SEXP pSEXP, SEXP qSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type d(dSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type As(AsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Bs(BsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type prev_ys(prev_ysSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type prev_sigmas(prev_sigmasSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type p(pSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_sigma_inp_k_pq_cpp(k, d, As, Bs, prev_ys, prev_sigmas, p, q, M));
    return rcpp_result_gen;
END_RCPP
}
// obj_fn_pq_cpp
double obj_fn_pq_cpp(arma::mat d, arma::mat As, arma::mat Bs, arma::mat ysq, unsigned int p, unsigned int q);
RcppExport SEXP _CurVol_obj_fn_pq_cpp(SEXP dSEXP, SEXP AsSEXP, SEXP BsSEXP, SEXP ysqSEXP, SEXP pSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type d(dSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type As(AsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Bs(BsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ysq(ysqSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type p(pSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(obj_fn_pq_cpp(d, As, Bs, ysq, p, q));
    return rcpp_result_gen;
END_RCPP
}
// compute_sigma_inp_k_q_cpp
double compute_sigma_inp_k_q_cpp(unsigned int k, arma::mat d, arma::mat As, arma::mat prev_ys, unsigned int q, int M);
RcppExport SEXP _CurVol_compute_sigma_inp_k_q_cpp(SEXP kSEXP, SEXP dSEXP, SEXP AsSEXP, SEXP prev_ysSEXP, SEXP qSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type d(dSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type As(AsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type prev_ys(prev_ysSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_sigma_inp_k_q_cpp(k, d, As, prev_ys, q, M));
    return rcpp_result_gen;
END_RCPP
}
// obj_fn_q_cpp
double obj_fn_q_cpp(arma::mat d, arma::mat As, arma::mat ysq, unsigned int q);
RcppExport SEXP _CurVol_obj_fn_q_cpp(SEXP dSEXP, SEXP AsSEXP, SEXP ysqSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type d(dSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type As(AsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ysq(ysqSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(obj_fn_q_cpp(d, As, ysq, q));
    return rcpp_result_gen;
END_RCPP
}
// compute_sigma_inp_k_x_cpp
double compute_sigma_inp_k_x_cpp(unsigned int k, arma::mat d, arma::mat As, arma::mat Bs, arma::mat Gs, arma::mat prev_ys, arma::mat prev_sigmas, arma::mat prev_x, int M);
RcppExport SEXP _CurVol_compute_sigma_inp_k_x_cpp(SEXP kSEXP, SEXP dSEXP, SEXP AsSEXP, SEXP BsSEXP, SEXP GsSEXP, SEXP prev_ysSEXP, SEXP prev_sigmasSEXP, SEXP prev_xSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type d(dSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type As(AsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Bs(BsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Gs(GsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type prev_ys(prev_ysSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type prev_sigmas(prev_sigmasSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type prev_x(prev_xSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_sigma_inp_k_x_cpp(k, d, As, Bs, Gs, prev_ys, prev_sigmas, prev_x, M));
    return rcpp_result_gen;
END_RCPP
}
// obj_fn_x_cpp
double obj_fn_x_cpp(arma::mat d, arma::mat As, arma::mat Bs, arma::mat Gs, arma::mat ysq, arma::mat xsq);
RcppExport SEXP _CurVol_obj_fn_x_cpp(SEXP dSEXP, SEXP AsSEXP, SEXP BsSEXP, SEXP GsSEXP, SEXP ysqSEXP, SEXP xsqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type d(dSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type As(AsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Bs(BsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Gs(GsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ysq(ysqSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type xsq(xsqSEXP);
    rcpp_result_gen = Rcpp::wrap(obj_fn_x_cpp(d, As, Bs, Gs, ysq, xsq));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CurVol_compute_sigma_inp_k_pq_cpp", (DL_FUNC) &_CurVol_compute_sigma_inp_k_pq_cpp, 9},
    {"_CurVol_obj_fn_pq_cpp", (DL_FUNC) &_CurVol_obj_fn_pq_cpp, 6},
    {"_CurVol_compute_sigma_inp_k_q_cpp", (DL_FUNC) &_CurVol_compute_sigma_inp_k_q_cpp, 6},
    {"_CurVol_obj_fn_q_cpp", (DL_FUNC) &_CurVol_obj_fn_q_cpp, 4},
    {"_CurVol_compute_sigma_inp_k_x_cpp", (DL_FUNC) &_CurVol_compute_sigma_inp_k_x_cpp, 9},
    {"_CurVol_obj_fn_x_cpp", (DL_FUNC) &_CurVol_obj_fn_x_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_CurVol(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
