# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib CurVol
#' @importFrom Rcpp sourceCpp
compute_sigma_inp_k_pq_cpp <- function(k, d, As, Bs, prev_ys, prev_sigmas, p, q, M) {
    .Call('_CurVol_compute_sigma_inp_k_pq_cpp', PACKAGE = 'CurVol', k, d, As, Bs, prev_ys, prev_sigmas, p, q, M)
}

#' @useDynLib CurVol
#' @importFrom Rcpp sourceCpp
obj_fn_pq_cpp <- function(d, As, Bs, ysq, p, q) {
    .Call('_CurVol_obj_fn_pq_cpp', PACKAGE = 'CurVol', d, As, Bs, ysq, p, q)
}

#' @useDynLib CurVol
#' @importFrom Rcpp sourceCpp
compute_sigma_inp_k_q_cpp <- function(k, d, As, prev_ys, q, M) {
    .Call('_CurVol_compute_sigma_inp_k_q_cpp', PACKAGE = 'CurVol', k, d, As, prev_ys, q, M)
}

#' @useDynLib CurVol
#' @importFrom Rcpp sourceCpp
obj_fn_q_cpp <- function(d, As, ysq, q) {
    .Call('_CurVol_obj_fn_q_cpp', PACKAGE = 'CurVol', d, As, ysq, q)
}

#' @useDynLib CurVol
#' @importFrom Rcpp sourceCpp
compute_sigma_inp_k_x_cpp <- function(k, d, As, Bs, Gs, prev_ys, prev_sigmas, prev_x, M) {
    .Call('_CurVol_compute_sigma_inp_k_x_cpp', PACKAGE = 'CurVol', k, d, As, Bs, Gs, prev_ys, prev_sigmas, prev_x, M)
}

#' @useDynLib CurVol
#' @importFrom Rcpp sourceCpp
obj_fn_x_cpp <- function(d, As, Bs, Gs, ysq, xsq) {
    .Call('_CurVol_obj_fn_x_cpp', PACKAGE = 'CurVol', d, As, Bs, Gs, ysq, xsq)
}

